# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Chiko
tagline:          'Aspiring Software engineer'
description:      'Thoughts, learnings and general sharebles from me.'
url:              http://chikomukwenha.co
baseurl:          /

author:
  name:           'Chiko'
  url:            https://twitter.com/therealchiko

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/therealchiko

gems: [jekyll-paginate]
