# Dependencies
markdown: kramdown
highlighter: rouge
extensions: [fenced_code_blocks]

# Permalinks
permalink: /:categories/:title/
#relative_permalinks: tru

# Setup
title: Chiko Mukwenha
tagline: Product Engineer
description: ""
url: http://chikomukwenha.co
baseurl: /
reading: /reading

author:
  name: "Chiko"
  url: https://twitter.com/therealchiko

paginate: 5

# Custom vars
version: 2.1.0

excerpt_separator: <!--more-->

github:
  repo: https://github.com/therealchiko

social:
  twitter: https://twitter.com/therealchiko

plugins: [jekyll-paginate,jekyll-feed]

defaults:
  -
    scope:
      path: "category"
    values:
      layout: "category"
