# Dependencies
markdown:         kramdown
highlighter:      rouge
extensions:       [fenced_code_blocks]

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Chiko Mukwenha
tagline:          'Software Developer'
description:      "I'm a full stack developer. I live in Sunshine City, a place near the bottom tip of Africa!"
url:              http://chikomukwenha.co
baseurl:          /

author:
  name:           'Chiko'
  url:            https://twitter.com/therealchiko

paginate:         5

# Custom vars
version:          2.1.0

excerpt_separator:  <!--more-->

github:
  repo:           https://github.com/therealchiko

social:
  twitter:        http://twitter.com/therealchiko

gems:             [jekyll-paginate]
