# Dependencies
markdown: kramdown
highlighter: rouge
extensions: [fenced_code_blocks]

# Permalinks
permalink: /:categories/:title/
#relative_permalinks: tru

# Setup
title: Chiko Mukwenha
tagline: Product Engineer
description: ""
url: http://chikomukwenha.co
baseurl: /
reading: /reading

author:
  name: "Chiko"
  url: https://twitter.com/therealchiko

# Custom vars
version: 2.1.0

excerpt_separator: <!--more-->

github:
  repo: https://github.com/therealchiko

social:
  twitter: https://twitter.com/therealchiko

plugins: [jekyll-feed, jekyll-paginate-v2]

defaults:
  -
    scope:
      path: "category"
    values:
      layout: "category"

############################################################
# Site configuration for the Jekyll 3 Pagination Gem
pagination:
  enabled: true
  per_page: 9
  permalink: '/page/:num/'
  title: ':title - Page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

reading:
  current_book: "Flutter Engineering by Majid Hajian"
upcoming:
  next_post: "How to use UUIDs in Flutter using Drift"
