# Dependencies
markdown:         redcarpet
highlighter:      rouge
extensions: [fenced_code_blocks]

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Chiko Mukwenha
tagline:          'Aspiring Software engineer'
description:      'Thoughts and learnings from the mind of a web developer.'
url:              http://chikomukwenha.co
baseurl:          /

author:
  name:           'Chiko'
  url:            https://twitter.com/therealchiko

paginate:         5

# Custom vars
version:          2.1.0

excerpt_separator:  <!--more-->

github:
  repo:           https://github.com/therealchiko

social:
  twitter:        http://twitter.com/therealchiko

gems: [jekyll-paginate]
